[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cash-collection"
version = "0.0.1"
readme = "README.md"

[tool.pytest.ini_options]
pythonpath = "src"
