# Generated by Django 5.0.6 on 2024-07-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_customer_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='is_frozen',
        ),
    ]
